### ISSUE TITLE
Consider rebranding

### ISSUE THREAD

**Issue by sghall** [deduced/bov-personal-portfolio#27]
Just spitballing here...but instead of your name maybe only refer to yourself on the site as "The Infamous Git Gaucho"? And then make vague references to requiring reimbursement for "stable fees" on consulting gigs. Build the mystery m'man.  You are totally free to use this great idea.

<img width="319" alt="screen shot 2017-08-10 at 2 18 09 pm" src="https://user-images.githubusercontent.com/4615775/29192604-d7e6dd58-7dd6-11e7-8e66-154fec59ad4e.png">

[Image at the noun project](https://thenounproject.com/search/?q=gaucho&i=615101) in case you need it.

Or maybe this one...now that's memorable...wtf

<img width="297" alt="screen shot 2017-08-10 at 2 32 08 pm" src="https://user-images.githubusercontent.com/4615775/29193106-c9d41eae-7dd8-11e7-891b-6c555a58c45e.png">

**Comment by deduced** [comment]
haha! I like it. Stay tuned for a version 2 borrowing the suggestions.

**Comment by sghall** [comment]
Nice. Seriously, looking good man.  Keep it up!
